version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:16.1
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: zvzdt/foodgram_backend
    env_file: ..mkdir/.env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: zvzdt/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.22.1
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
      - frontend