# Generated by Django 3.2.3 on 2023-12-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_ingredients_recipeingredients_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
